import { describe, expect, it } from "vitest";
import { runReviewArchitecture } from "../src/core/engine";
import { createLogger } from "../src/core/logging";
import { loadArchitectureById } from "../src/core/manifest";
import type { ReviewProvider } from "../src/core/types";

function createTestProvider(): ReviewProvider {
  return {
    async review(): Promise<string> {
      return JSON.stringify(
        {
          summary: "Test review summary.",
          riskLevel: "low",
          findings: [
            {
              severity: "low",
              title: "Test finding",
              detail: "Found in test code.",
            },
          ],
          todos: [],
          notes: ["Generated by test provider."],
        },
        null,
        2,
      );
    },
  };
}

describe("review engine", () => {
  it.each(["single-pass", "iterative", "parallel"] as const)(
    "runs %s end-to-end with the test provider",
    async (architectureId) => {
      const architecture = await loadArchitectureById(
        "prompts",
        architectureId,
      );
      const logs: string[] = [];
      const logger = createLogger((entry) => {
        logs.push(`${entry.level}:${entry.message}`);
      });

      const result = await runReviewArchitecture({
        architecture,
        request: {
          architectureId,
          files: [
            {
              path: "src/example.ts",
              name: "example.ts",
              content: "console.log('test');\n",
            },
          ],
        },
        provider: createTestProvider(),
        logger,
        maxContextChars: 8000,
      });

      expect(result.report.markdown).toContain(architecture.label);
      expect(result.stageOutputs.length).toBeGreaterThan(0);
      expect(
        logs.some((line) => line.startsWith("info:Starting review run")),
      ).toBe(true);

      if (architectureId === "single-pass") {
        expect(result.stageOutputs).toHaveLength(1);
      }

      if (architectureId === "iterative") {
        expect(result.stageOutputs).toHaveLength(6);
      }

      if (architectureId === "parallel") {
        expect(result.stageOutputs).toHaveLength(7);
      }
    },
  );
});
